### ISSUE TITLE
Feature Request: Installable library

### ISSUE THREAD

**Issue by fmorgner** [Murthy10/cppGeoTile#5]
Currently, the library can only be consumed in any meaningful way when adding it as a subproject, since it can not easily be installed. I would suggest adding a suitable installation configuration to build configuration.

I would be happy to contribute such a configuration if @Murthy10 considers this a useful addition.

**Comment by Murthy10** [comment]
Just awesome!

@fmorgner  Thanks a lot for all your advises and your contribution.

**Comment by fmorgner** [comment]
Closed by 3e30248
