### ISSUE TITLE
Feature Request: Conan Package

### ISSUE THREAD

**Issue by fmorgner** [Murthy10/cppGeoTile#6]
Related to #5, the library is currently available only in source form. It would be cool to have a conan.io package for this library, to make it easier for people to find and consume the library.

I would be happy to contribute such a configuration if @Murthy10 sees this as something worth spending time on.

**Comment by Murthy10** [comment]
That would be great. (else I have to dig into that topic and somehow do it on my own)

**Comment by fmorgner** [comment]
closed by 1905dad27ea998e0a0afc985573683e0e4e98079 and 890e7ca7cf36312bf6dff3e9d175a206423fbc58
