### ISSUE TITLE
Improvement: Remove GoogleTest submodule

### ISSUE THREAD

**Issue by fmorgner** [Murthy10/cppGeoTile#7]
GoogleTest is a widely used testing framework and enjoys the luxury of being present in a large number of package managers for all mainstream Linux distributions as well as Apple macOS (via homebrew) and Microsoft Windows (via chocolatey).

I suggest to remove the git submodule and rely on the user having installed GoogleTest on their system. Thus, we could enjoy easier configuration and better integration into CMake. I believe that shifting the burden of installing GoogleTest on the user would acceptable, since most users wont be using the unittests anyway.

**Comment by Darnor** [comment]
Sounds good to me, let's see what @Murthy10 thinks.

As a side note, would you disable the tests as a default as well, so users do not have to set any variables in their CMake config?

**Comment by Murthy10** [comment]
I agree with that and appreciate the advice.
(will tackle that)

**Comment by fmorgner** [comment]
I disabled the tests by default. e5fa823 now has no submodule anymore and relies on a system-wide installed GTest.
