### ISSUE TITLE
Bug: unexpected output from Tile::getQuadTree() 

### ISSUE THREAD

**Issue by gallottino** [Murthy10/cppGeoTile#9]
Hi!
First of all thank you for this library. I need it to generate a quadkey from latitude and longitude values. I know about your pyGeoTile library, but for my purpose i prefer to use C++. 

The first unexpected output come from the Tile::getQuadTree() function. The code, infact, seems to be unable to generate quadkey with the "3" value in the generated string. Doing many test i can't obtain the right value of quadkey, also compared with pyGeoTile library. 

I think that the trouble is in the rounding of value when the TMS is generated (it appears in my case with zoom > 16). Another problem come from the iterator osstream :
`if (digit > 2)
        {
            digit %= 2;
        }`
In this way it is impossible to have the  digit "3". 

For this reason i changed some part of code in this way: 2a03b7c.

Let me know about it. It is my first contribution at all. Do I have to make a pull request?

**Comment by Murthy10** [comment]
Hi, cool that this repo gets used. 

A PR would be great and maybe you can add a test that covers the bug you found.

**Comment by gallottino** [comment]
@Murthy10 Thank you for the very quick answer. I added a test how you said.

**Comment by gallottino** [comment]
Solved here: #10
